---
- name: Make sure gitea_register_email_confirm is false when gitea_register_manual_confirm is true
  ansible.builtin.fail:
    msg: |
      To manually confirm registrations,
      gitea_register_email_confirm needs to be false
      and gitea_register_manual_confirm should be true.
  when: gitea_register_manual_confirm | bool and gitea_register_email_confirm | bool

- name: DEBUG
  ansible.builtin.debug:
    msg: "gitea_themes: {{ gitea_themes }}"

- name: "Configure gitea"
  become: true
  ansible.builtin.template:
    src: "templates/gitea.ini.j2"
    dest: "{{ gitea_configuration_path }}/gitea.ini"
    owner: "{{ gitea_user }}"
    group: "{{ gitea_group }}"
    mode: "0640"
  notify: "systemctl restart gitea"

- name: "Service gitea"
  become: true
  ansible.builtin.systemd_service:
    name: gitea
    state: started
    enabled: true
  when: ansible_service_mgr == "systemd"
